source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'OctopusAppTest' do
    pod 'Octopus-iOS', '~> 2.0.0'
end

target 'OctopusAppTestUITests' do
    pod 'Octopus-iOS', '~> 2.0.0'
end

target 'PerformanceTest' do
    pod 'Octopus-iOS', '~> 2.0.0'
end
