source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'OctopusAppTest' do
    pod 'Octopus-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/octopus/v1.2/binding/ios/Octopus-iOS.podspec'
end

target 'OctopusAppTestUITests' do
    pod 'Octopus-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/octopus/v1.2/binding/ios/Octopus-iOS.podspec'
end

target 'PerformanceTest' do
    pod 'Octopus-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/octopus/v1.2/binding/ios/Octopus-iOS.podspec'
end
