source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'OctopusDemo' do
    pod 'Octopus-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/octopus/v2.0-ios/binding/ios/Octopus-iOS.podspec'
end
