source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'OctopusDemo' do
    pod 'Octopus-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/octopus/app-center/binding/ios/Octopus-iOS.podspec'
end

target 'OctopusDemoUITests' do
    pod 'Octopus-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/octopus/app-center/binding/ios/Octopus-iOS.podspec'
end
