name: Run demo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  model_path:
    required: true
  audio_path:
    required: true
  index_path:
    required: true
  search_phrase:
    required: true

runs:
  using: "composite"
  steps:
  - name: Indexing with performance measuring
    run: >
      ./build/octopus_index_demo
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      -w ${{ inputs.audio_path }}
      -i ${{ inputs.index_path }}
    working-directory: demo/c
    shell: bash

  - name: Searching
    run: >
      ./build/octopus_search_demo
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      -i ${{ inputs.index_path }}
      -s ${{ inputs.search_phrase }}
    working-directory: demo/c
    shell: bash
