name: Android Performance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'

  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'

defaults:
  run:
    working-directory: demo/android/OctopusDemo

jobs:
  build:
    name: Run Android Speed Tests on AppCenter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [single-android, 32bit-android]
        include:
        - device: single-android
          indexPerformanceThresholdSec: 1.5
          searchPerformanceThresholdSec: 0.004
        - device: 32bit-android
          indexPerformanceThresholdSec: 8
          searchPerformanceThresholdSec: 0.004

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Number of Iterations
      run: echo numTestIterations="30" >> local.properties

    - name: Inject Index Performance Threshold
      run: echo indexPerformanceThresholdSec="${{ matrix.indexPerformanceThresholdSec }}" >> local.properties

    - name: Inject Search Performance Threshold
      run: echo searchPerformanceThresholdSec="${{ matrix.searchPerformanceThresholdSec }}" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleAndroidTest

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Octopus-Android"
        --devices "Picovoice/${{ matrix.device }}"
        --app-path octopus-demo-app/build/outputs/apk/debug/octopus-demo-app-debug.apk
        --test-series "octopus-android"
        --locale "en_US"
        --build-dir octopus-demo-app/build/outputs/apk/androidTest/debug

