name: C Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'

jobs:
  build-index-demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Index Demo
      run: |
        cmake -S demo/c/. -B demo/c/build
        cmake --build demo/c/build --target octopus_index_demo

  build-search-demo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Search Demo
      run: |
        cmake -S demo/c/. -B demo/c/build
        cmake --build demo/c/build --target octopus_search_demo
