name: C Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '!demo/c/README.md'
      - '.github/workflows/c-demos.yml'
      - 'demo/c/**'
      - 'lib/common/**'
      - 'lib/mac/**'
      - 'lib/windows/**'
      - 'res/audio_samples/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '!demo/c/README.md'
      - '.github/workflows/c-demos.yml'
      - 'demo/c/**'
      - 'lib/common/**'
      - 'lib/mac/**'
      - 'lib/windows/**'
      - 'res/audio_samples/**'


defaults:
  run:
    working-directory: demo/c

jobs:
  build-demo-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x86_64
        - os: windows-latest
          platform: windows
          arch: amd64
        - os: macos-latest
          platform: mac
          arch: x86_64

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python '3.10'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create build directory
      run: cmake -B ./build

    - name: Build demo
      run: cmake --build ./build

    - name: Install dependencies
      run: pip install -r test/requirements.txt

    - name: Test
      run: python test/test_octopus_c.py ${{secrets.PV_VALID_ACCESS_KEY}} ${{ matrix.platform }} ${{ matrix.arch }}
