name: C Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'
      - '.github/workflows/c-demos.yml'

  pull_request:
    branches: [ main ]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'
      - '.github/workflows/c-demos.yml'

jobs:
  build-demos-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x86_64
          ext: so
        - os: windows-latest
          platform: windows
          arch: amd64
          ext: dll
        - os: macos-latest
          platform: mac
          arch: x86_64
          ext: dylib

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Search Demo
      run: |
        cmake -S demo/c/. -B demo/c/build
        cmake --build demo/c/build

    - uses: ./.github/actions/c-demo
      name: Run demo
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_octopus.${{ matrix.ext }}
        model_path: ../../lib/common/param/octopus_params.pv
        audio_path: ../../res/audio/multiple_keywords.wav
        index_path: ../../index.oif
        search_phrase: picovoice