name: iOS AppCenter Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'demo/ios'
      - '!demo/ios/README.md'
  pull_request:
    branches: [ main ]
    paths: 
      - 'demo/ios'
      - '!demo/ios/README.md'
      
defaults:
  run:
    working-directory: demo/ios/OctopusDemo
    
jobs:
  build:
    name: Run iOS Tests on AppCenter
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Install AppCenter CLI
        run: npm install -g appcenter-cli

      - name: Make build dir
        run: mkdir ddp

      - name: Run Cocoapods
        run: pod install

      - name: Inject AppID
        run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
          OctopusDemoUITests/OctopusDemoUITests.swift

      - name: XCode Build
        run: xcrun xcodebuild build-for-testing 
          -configuration Debug 
          -workspace OctopusDemo.xcworkspace
          -sdk iphoneos 
          -scheme OctopusDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Run Tests on AppCenter
        run: appcenter test run xcuitest 
          --token ${{secrets.APPCENTERAPITOKEN}}
          --app "Picovoice/Octopus-iOS"
          --devices "Picovoice/ios-single" 
          --test-series "octopus-ios"
          --locale "en_US" 
          --build-dir ddp/Build/Products/Debug-iphoneos
