name: iOS Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/ios/OctopusDemo/**'
      - '.github/workflows/ios-demos.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/ios/OctopusDemo/**'
      - '.github/workflows/ios-demos.yml'

defaults:
  run:
    working-directory: demo/ios/OctopusDemo

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Install AppCenter CLI
        run: npm install -g appcenter-cli

      - name: Make build dir
        run: mkdir ddp

      - name: Run Cocoapods
        run: pod install

      - name: Build
        run: xcrun xcodebuild build
          -configuration Debug
          -workspace OctopusDemo.xcworkspace
          -sdk iphoneos
          -scheme OctopusDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO