name: iOS Performance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'lib/ios/**'
      - 'lib/common/**'
      - '.github/workflows/ios-perf.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'lib/ios/**'
      - 'lib/common/**'
      - '.github/workflows/ios-perf.yml'

defaults:
  run:
    working-directory: binding/ios/OctopusAppTest

jobs:
  build:
    name: Run iOS Tests on BrowserStack
    runs-on: macos-latest

    strategy:
      matrix:
        device: [ ios-perf ]
        include:
        - device: ios-perf
          indexPerformanceThresholdSec: 1.5
          searchPerformanceThresholdSec: 0.001

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run:
          pip3 install requests

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Make build dir
        run: mkdir ddp

      - name: Run Cocoapods
        run: pod install

      - name: Inject AppID
        run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
          PerformanceTest/PerformanceTest.swift

      - name: Inject Number of Iterations
        run: sed -i '.bak' 's:{NUM_TEST_ITERATIONS}:30:'
          PerformanceTest/PerformanceTest.swift

      - name: Inject Index Performance Threshold
        run: sed -i '.bak'
          '1,/{INDEX_PERFORMANCE_THRESHOLD_SEC}/s/{INDEX_PERFORMANCE_THRESHOLD_SEC}/${{ matrix.indexPerformanceThresholdSec }}/'
          PerformanceTest/PerformanceTest.swift

      - name: Inject Search Performance Threshold
        run: sed -i '.bak'
          '1,/{SEARCH_PERFORMANCE_THRESHOLD_SEC}/s/{SEARCH_PERFORMANCE_THRESHOLD_SEC}/${{ matrix.searchPerformanceThresholdSec }}/'
          PerformanceTest/PerformanceTest.swift

      - name: XCode Build
        run: xcrun xcodebuild build-for-testing
          -configuration Debug
          -workspace OctopusAppTest.xcworkspace
          -sdk iphoneos
          -scheme PerformanceTest
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Generating ipa
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          mkdir Payload &&
          cp -r OctopusAppTest.app Payload &&
          zip --symlinks -r OctopusAppTest.ipa Payload &&
          rm -r Payload

      - name: Zipping Tests
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          zip --symlinks -r PerformanceTest.zip PerformanceTest-Runner.app

      - name: Run tests on BrowserStack
        run: python3 ../../../script/automation/browserstack.py
          --type xcuitest
          --username "${{secrets.BROWSERSTACK_USERNAME}}"
          --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
          --project_name "Octopus-iOS-Performance"
          --devices "${{ matrix.device }}"
          --app_path "ddp/Build/Products/Debug-iphoneos/OctopusAppTest.ipa"
          --test_path "ddp/Build/Products/Debug-iphoneos/PerformanceTest.zip"
