name: Python Performance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'binding/python/test_octopus_perf.py'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/windows/**'
      - 'res/audio/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/python/test_octopus_perf.py'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/windows/**'
      - 'res/audio/**'

defaults:
  run:
    working-directory: binding/python

jobs:
  perf:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          index_performance_threshold_sec: 2.2
          search_performance_threshold_sec: 0.001
        - os: windows-latest
          index_performance_threshold_sec: 2.2
          search_performance_threshold_sec: 0.001
        - os: macos-latest
          index_performance_threshold_sec: 2.8
          search_performance_threshold_sec: 0.001

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python '3.10'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Pre-build dependencies
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test
      run: python test_octopus_perf.py ${{secrets.PV_VALID_ACCESS_KEY}} 100 ${{ matrix.index_performance_threshold_sec }} ${{ matrix.search_performance_threshold_sec }}
