name: Web Performance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'lib/wasm/**'
      - 'lib/common/**'
      - '.github/workflows/web-perf.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'lib/wasm/**'
      - 'lib/common/**'
      - '.github/workflows/web-perf.yml'

defaults:
  run:
    working-directory: binding/web

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]
        include:
        - indexPerformanceThresholdSec: 2.4
          searchPerformanceThresholdSec: 0.015

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Copy libs
      run: yarn copywasm

    - name: Build
      run: yarn build

    - name: Prepare Test
      run: yarn setup-test

    - name: Test
      run: yarn test-perf --env ACCESS_KEY=${{secrets.PV_VALID_ACCESS_KEY}},NUM_TEST_ITERATIONS=20,INDEX_PERFORMANCE_THRESHOLD_SEC=${{matrix.indexPerformanceThresholdSec}},SEARCH_PERFORMANCE_THRESHOLD_SEC=${{matrix.searchPerformanceThresholdSec}}
